# Your Website Title
title: Hom Wuu

# Your Website URL
url: 'http://drawtosword.github.io'

# Leave it default
baseurl: '' 

# Google Analytics
ga_index: UA-XXXXXXXX-X
ga_cv: UA-XXXXXXXX-X

# Index page and Profile Information
name: Hom Wuu
tagline: Developer of java
pic: portrait.png
description: Full Stack Developer
description_tiny: 'A weak programmer, Do the smallest things'
email: wu_hom910428@163.com
website: drawtosword.github.io # do not add http://
#linkedin: realmelvinchng
github: drawtosword
#twitter: '@realmelvinchng'

# Files or folders to be excluded
exclude: [gitbook_source_code/]

# All the plugins for Jekyll
plugins:
  - jekyll-sitemap
  - wdm